version: '3.8'

services:
  backend:
    extends:
      file: docker-compose.base.yml
      service: backend
    build: 
      context: .
      dockerfile: Dockerfile.backend
      target: build_for_test
    working_dir: /app/backend
    command: npx vitest --run --dir ./test/IncanGold/unit_test

  db:
    extends:
      file: docker-compose.base.yml
      service: db